# GoReleaser configuration for harvester-enable-nested-virt
version: 2

# NOTE: If you fork this repository and want to publish to your own registry,
# update the KO_DOCKER_REPO environment variable in .github/workflows/release.yml

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  - id: webhook
    main: ./cmd/webhook
    binary: webhook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

kos:
  - id: webhook-ko
    build: webhook
    base_image: cgr.dev/chainguard/static:latest
    tags:
      - '{{.Tag}}'
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: '{{.Date}}'
      org.opencontainers.image.title: '{{.ProjectName}}'
      org.opencontainers.image.revision: '{{.FullCommit}}'
      org.opencontainers.image.version: '{{.Version}}'
      org.opencontainers.image.source: '{{.GitURL}}'

checksum:
  name_template: 'checksums.txt'

# SBOM generation
sboms:
  - artifacts: archive
    ids:
      - webhook

# Sign artifacts (disabled in snapshot mode)
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

# Docker image signing (disabled in snapshot mode)
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: all
    output: true
    args:
      - 'sign'
      - '${artifact}'
      - "--yes" # needed on cosign 2.0.0+

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Enhancements'
      regexp: '^.*?enhance(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## Release {{.Version}}
    
    This release includes the webhook binary and container image for enabling nested virtualization in Harvester VMs.
    
    ### Container Images
    
    Multi-arch container images are available at:
    - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}
    - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest
    
    Supported architectures: `linux/amd64`, `linux/arm64`

    ## Helm Chart
    
    Install via OCI registry:
    
    ```bash
    helm install harvester-enable-nested-virt oci://ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/charts/harvester-enable-nested-virt --version {{ .Version }}
    ```
